CREATE TABLE IF NOT EXISTS `policy` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `policyNumber` VARCHAR(50) NOT NULL UNIQUE,
  `insuredName` VARCHAR(100) NOT NULL,
  `mobile` VARCHAR(15),
  `email` VARCHAR(100),
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `company` VARCHAR(100) NOT NULL,
  `business` VARCHAR(50) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `status` VARCHAR(50) DEFAULT 'Live Policy',
  `vehicleType` VARCHAR(50),
  `vehicleNumber` VARCHAR(20),
  `make` VARCHAR(50),
  `model` VARCHAR(50),
  `year` VARCHAR(4),
  `basicPremium` DECIMAL(10,2),
  `odPremium` DECIMAL(10,2),
  `tpPremium` DECIMAL(10,2),
  `ncbDiscount` DECIMAL(10,2),
  `addonPremium` DECIMAL(10,2),
  `gst` DECIMAL(10,2),
  `totalPremium` DECIMAL(10,2),
  `paymentMode` VARCHAR(50),
  `paymentReference` VARCHAR(100),
  `healthPlan` VARCHAR(50),
  `sumInsured` DECIMAL(10,2),
  `age` INT,
  `preExisting` VARCHAR(3),
  `travelType` VARCHAR(50),
  `destination` VARCHAR(100),
  `tripDuration` INT,
  `commissionAmount` DECIMAL(10,2),
  `commissionPercentage` DECIMAL(5,2),
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 